// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import LikertSurveyConcept from "./LikertSurvey/LikertSurveyConcept.ts";
import MediaManagementConcept from "./MediaManagement/MediaManagementConcept.ts";
import RenderingConcept from "./Rendering/RenderingConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SessionConcept from "./Session/SessionConcept.ts";
import TextExtractionConcept from "./TextExtraction/TextExtractionConcept.ts";
import TranslationConcept from "./Translation/TranslationConcept.ts";
import UserConcept from "./User/UserConcept.ts";

export type { default as LikertSurveyConcept } from "./LikertSurvey/LikertSurveyConcept.ts";
export type { default as MediaManagementConcept } from "./MediaManagement/MediaManagementConcept.ts";
export type { default as RenderingConcept } from "./Rendering/RenderingConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SessionConcept } from "./Session/SessionConcept.ts";
export type { default as TextExtractionConcept } from "./TextExtraction/TextExtractionConcept.ts";
export type { default as TranslationConcept } from "./Translation/TranslationConcept.ts";
export type { default as UserConcept } from "./User/UserConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const LikertSurvey = Engine.instrumentConcept(new LikertSurveyConcept(db));
export const MediaManagement = Engine.instrumentConcept(new MediaManagementConcept(db));
export const Rendering = Engine.instrumentConcept(new RenderingConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Session = Engine.instrumentConcept(new SessionConcept(db));
export const TextExtraction = Engine.instrumentConcept(new TextExtractionConcept(db));
export const Translation = Engine.instrumentConcept(new TranslationConcept(db));
export const User = Engine.instrumentConcept(new UserConcept(db));
